sudo: required
services:
  - docker
  
before_install:
  - docker build -t balazsszilardtoth/docker-react -f Dockerfile.dev .
  
script:
  - docker run balazsszilardtoth/docker-react npm run test -- --coverage