sudo: required
services:
  - docker
  
before_install:
  - docker build -t allmyles/docker-react -f Dockerfile.dev .
  
script:
  - docker run allmyles/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  name: "udemy-docker-react"
  env: "UdemyDockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-202086208544"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
    